import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import MainHeader from "@/components/header";
import { Inter } from "next/font/google";
import "./globals.css";
import "./quill-custom.css";
import "react-quill/dist/quill.snow.css";
import Footer from "@/components/footer";
import { ScrollTopButton } from "@/components/custom/scroll-top-button";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OXOdb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={<Loading />}>
            <div className="text-character bg-fixed bg-cover bg-center h-full w-full min-h-screen bg-[url('../../public/images/Background.png')] dark:bg-[url('../../public/images/Background-dark.png')]">
              <ScrollTopButton />
              <MainHeader />
              {children}
              <Footer />
              <Toaster />
            </div>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
